name: goremad-ide-frontend

on:
  merge_request:
    branches: ["main"]
    paths:
      - ide/frontend/**
  push:
    branches: ["main"]
    paths:
      - ide/frontend/**

env:
  PROJECT_NAME: goremad-ide-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: frontend
          tags: ${{ vars.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }},${{ vars.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo "Deploying to production"
