name: goremad-ide-principal

on:
  push:
    branches: ["main"]
    paths:
      - principal/**

env:
  PROJECT_NAME: goremad-ide-principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: principal
          build-args: BASE_URL=${{ vars.BASE_URL }}
          tags: ${{ vars.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }},${{ vars.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build # Este trabajo depende del éxito del trabajo de construcción
    steps:
      # Despliegue en producción mediante SSH
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/geogoremad
            docker compose pull
            docker compose up -d
            yes | docker system prune -a
